sudo: required
services:
  - docker

before_install:
  - docker build -t <docker_username>/<repo_name> -f Dockerfile.dev . 

script:
  - docker run -e CI=true <docker_username>/<repo_name> npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "s3bucketname"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
